version: '3.8'
services:
  backend:
    container_name: dream_nest_backend
    build:
      context: ./server  # Actualiza esta línea con la ubicación correcta del backend
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/Dream_Nest
      - JWT_SECRET=fe3f81071b49f47ade580aef90dea7f9

  frontend:
    container_name: dream_nest_frontend
    build:
      context: ./client  # Actualiza esta línea con la ubicación correcta del frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    container_name: dream_nest_mongo
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret

volumes:
  mongo-data:
