version: '3.8'
services:
  app:
    build:
      context: ./src/BackEnd # Establecer el contexto de construcción al directorio del backend
      dockerfile: Dockerfile # Asegúrate de que el Dockerfile esté en src/BackEnd
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./src/BackEnd:/usr/src/app # Mapear el código fuente para desarrollo
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/DbConnectedTourism
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
